"""Uniform JSON error handling.

Two goals:

* clients always receive the same envelope
  ``{"error": {"code": ..., "message": ..., "details": {...}}}``;
* internal details (stack traces, SQL, file paths) never leak to the client
  (OWASP A05:2021 - Security Misconfiguration).
"""

from __future__ import annotations

from typing import Any, Dict, Optional, Tuple

from flask import Flask, Response, jsonify
from pydantic import ValidationError
from werkzeug.exceptions import HTTPException

from app.security.sanitize import sanitize_text


class ApiError(Exception):
    """An error that is safe to render back to the client."""

    def __init__(
        self,
        status_code: int,
        code: str,
        message: str,
        details: Optional[Dict[str, Any]] = None,
        headers: Optional[Dict[str, str]] = None,
    ) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.code = code
        self.message = message
        self.details = details or {}
        self.headers = headers or {}


def error_response(
    status_code: int,
    code: str,
    message: str,
    details: Optional[Dict[str, Any]] = None,
    headers: Optional[Dict[str, str]] = None,
) -> Tuple[Response, int]:
    """Build the canonical JSON error response."""
    payload: Dict[str, Any] = {"error": {"code": code, "message": message}}
    if details:
        payload["error"]["details"] = details
    response = jsonify(payload)
    for name, value in (headers or {}).items():
        response.headers[name] = value
    return response, status_code


_HTTP_CODES = {
    400: "bad_request",
    401: "unauthorized",
    403: "forbidden",
    404: "not_found",
    405: "method_not_allowed",
    409: "conflict",
    413: "payload_too_large",
    415: "unsupported_media_type",
    422: "validation_error",
    429: "rate_limited",
    500: "internal_error",
}


def _validation_details(exc: ValidationError) -> Dict[str, Any]:
    """Turn a pydantic error into a compact, sanitised, client-safe structure."""
    fields: Dict[str, Any] = {}
    for err in exc.errors():
        location = ".".join(str(part) for part in err.get("loc", ())) or "__root__"
        # The message is generated by pydantic, but the field path can echo
        # attacker-controlled key names, so it is escaped as well.
        fields[sanitize_text(location)] = sanitize_text(str(err.get("msg", "invalid value")))
    return {"fields": fields}


def register_error_handlers(app: Flask) -> None:
    """Attach every JSON error handler to ``app``."""

    @app.errorhandler(ApiError)
    def _handle_api_error(exc: ApiError) -> Tuple[Response, int]:
        return error_response(exc.status_code, exc.code, exc.message, exc.details, exc.headers)

    @app.errorhandler(ValidationError)
    def _handle_validation_error(exc: ValidationError) -> Tuple[Response, int]:
        return error_response(
            422, "validation_error", "Request payload failed validation.", _validation_details(exc)
        )

    @app.errorhandler(HTTPException)
    def _handle_http_exception(exc: HTTPException) -> Tuple[Response, int]:
        status = exc.code or 500
        code = _HTTP_CODES.get(status, "http_error")
        # werkzeug descriptions are static strings, safe to forward.
        message = exc.description or code.replace("_", " ").title()
        headers: Dict[str, str] = {}
        if status == 401:
            headers["WWW-Authenticate"] = "Bearer"
        return error_response(status, code, message, headers=headers)

    @app.errorhandler(Exception)
    def _handle_unexpected(exc: Exception) -> Tuple[Response, int]:
        # Log with traceback server-side, return an opaque message to the client.
        app.logger.exception("unhandled.exception", extra={"event": "unhandled.exception"})
        return error_response(500, "internal_error", "An internal error occurred.")
